-- V1.0.2__add_columns.sql
-- Add marketing and lifecycle attributes

USE SCHEMA ANALYTICS.CORE;

ALTER TABLE DIM_CUSTOMER
ADD COLUMN IF NOT EXISTS
    CUSTOMER_SEGMENT VARCHAR,
    IS_ACTIVE        BOOLEAN DEFAULT TRUE;

ALTER TABLE FACT_ORDERS
ADD COLUMN IF NOT EXISTS
    ORDER_STATUS VARCHAR;
