-- V1.2.0__create_core_tables.sql
USE DATABASE {{ db_name }};
USE SCHEMA {{ core_schema }};

CREATE TABLE IF NOT EXISTS DIM_CUSTOMER (
  CUSTOMER_ID   VARCHAR NOT NULL,
  CUSTOMER_NAME VARCHAR,
  EMAIL         VARCHAR,
  CREATED_AT    TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT    TIMESTAMP_NTZ,
  PRIMARY KEY (CUSTOMER_ID)
);

CREATE TABLE IF NOT EXISTS FACT_ORDERS (
  ORDER_ID      VARCHAR NOT NULL,
  CUSTOMER_ID   VARCHAR NOT NULL,
  ORDER_DATE    DATE,
  ORDER_AMOUNT  NUMBER(12,2),
  CREATED_AT    TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ORDER_ID)
);
